server:
  port: 9412
spring:
  application:
    name: open-zipkin-kafka-client
  zipkin:
    base-url: http://127.0.0.1:9411  
  cloud:
    stream:
      kafka:
        binder:
          brokers: zookeeper01:9092,zookeeper02:9092,zookeeper03:9092
          zkNodes: zookeeper01:2181,zookeeper02:2181,zookeeper03:2181 #,10.10.68.200:2181,10.10.68.201:2181
  sleuth:
    sampler:
      percentage: 1.0  
    rxjava:
      schedulers:
        ignoredthreads: HystrixMetricPoller,^RxComputation.*$,^RxIoScheduler.*$ #忽略rxjava相关线程，防止产生无意义的span
        
        
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 12000 #hystix失败超时时间判定        
      
logging:
  level:
    root: INFO
    org.springframework.cloud.sleuth: DEBUG



eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    serviceUrl:
        defaultZone: http://134.224.249.39:1111/eureka/

    