server:
  port: 9411
spring:
  application:
    name: open-zipkin-kafka-server
  sleuth:
    enabled: false
  sampler:
    percentage: 1.0
  cloud:
    stream:
      kafka:
        binder:
          brokers: zookeeper01:9092,zookeeper02:9092,zookeeper03:9092
          zkNodes: zookeeper01:2181,zookeeper02:2181,zookeeper03:2181 #,10.10.68.200:2181,10.10.68.201:2181
          min-partition-count: 3 
          auto-add-partitions: true
          replication-factor: 3
logging:
  level:
    root: INFO
    org: DEBUG
    com: DEBUG
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    serviceUrl:
        defaultZone: http://134.224.249.39:1111/eureka/

zipkin:
  storage:
    type: elasticsearch
    elasticsearch:
      cluster: owen
      hosts: http://130.75.131.233:9200,http://130.75.131.234:9200,http://130.75.131.235:9200
      index: zipkin
      index-shards: 5
      index-replicas: 1

    