server:
  port: 9412
spring:
  application:
    name: open-zipkin-memery-client
  zipkin:
    enabled: true
    base-url: http://open-zipkin-memery-server/ 
    locator:
      discovery:
        enabled: true
  sleuth:
    sampler:
      percentage: 1.0
    rxjava:
      schedulers:
        ignoredthreads: HystrixMetricPoller,^RxComputation.*$,^RxIoScheduler.*$ #忽略rxjava相关线程，防止产生无意义的span
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 12000 #hystix失败超时时间判定        
      
logging:
  level:
    root: INFO
    org.springframework.cloud.sleuth: DEBUG

eureka:
  client:
    serviceUrl:
      defaultZone:  http://127.0.0.1:1111/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${spring.application.instance_id:${server.port}}
    lease-renewal-interval-in-seconds: 5  #每隔几秒告诉eureka服务器我还存活，用于心跳检测
    lease-expiration-duration-in-seconds: 10 #如果心跳检测一直没有发送，10秒后会从eureka服务器中将此服务剔除s