server:
  port: 9410
spring:
  application:
    name: open-zipkin-memery-server
logging:
  level:
    root: INFO
    org.springframework.cloud.sleuth: DEBUG #监控行为


eureka:
  client:
    serviceUrl:
      defaultZone:  http://127.0.0.1:1111/eureka
    register-with-eureka: true  
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${spring.application.instance_id:${server.port}}
    lease-renewal-interval-in-seconds: 5  #每隔几秒告诉eureka服务器我还存活，用于心跳检测
    lease-expiration-duration-in-seconds: 10 #如果心跳检测一直没有发送，10秒后会从eureka服务器中将此服务剔除s
