server:
  port: 8089
  context-path: /uniServiceAccess

jasypt:  
  encryptor:  
    #这里可以理解成是加解密的时候使用的密钥  
    password: neusoft

spring:
  datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name:  oracle.jdbc.OracleDriver
      url: jdbc:oracle:thin:@130.75.1.11:2268:jxcrm
      username: crm_owner_user
      password: C_O_U_2013
      filters: stat,wall
  main:
    show-banner: false
  redis:
    cluster:
      nodes:
        134.224.249.36:7000,134.224.249.37:7000,134.224.249.38:7000,134.224.249.36:7001,134.224.249.37:7001,134.224.249.38:7001
    timeout: 1000 # 连接超时时间（毫秒）
    pool:
      max-active: 10  # 连接池最大连接数（使用负值表示没有限制）
      max-idle: 8     # 连接池中的最大空闲连接
      min-idle: 2     # 连接池中的最小空闲连接
      max-wait: 100   # 连接池最大阻塞等待时间（使用负值表示没有限制）      
  
    
    
    

mybatis:
  config-location: classpath:mybatis.cfg.xml
  mapper-locations: classpath*:com/open/**/dao/*.xml  
  
logging:
  level:
    root: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
    com.open: DEBUG  