server:
  port: 8890
spring:
  application:
    name: open-auth-gateway
  datasource:
      type: com.alibaba.druid.pool.DruidDataSource
#      driver-class-name:  oracle.jdbc.OracleDriver
#      url: jdbc:oracle:thin:@127.0.0.1:1521:orcl
#      username: crm_owner_user
#      password: bss_crm_test
#      filters: stat,wall
################## mysql start ############################
      driver-class-name:  com.mysql.jdbc.Driver
      #     192.168.3.150   130.75.131.211
      url: jdbc:mysql://localhost:3306/boot_security?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
      username: root
      password: actbd
      filters: stat,wall
################### mysq end l##########################
  redis:
################### redis 单机版 start ########################## 
    host: 127.0.0.1
    port: 18888
    timeout: 3000
    database: 1
################### redis 单机版 end ##########################   
#    cluster:
#      nodes: 192.168.3.157:7000,192.168.3.158:7000,192.168.3.159:7000,192.168.3.157:7001,192.168.3.158:7001,192.168.3.159:7001
##        #130.75.131.237:7000,130.75.131.238:7000,130.75.131.239:7000,130.75.131.237:7001,130.75.131.238:7001,130.75.131.239:7001
#        #192.168.3.157:7000,192.168.3.158:7000,192.168.3.159:7000,192.168.3.157:7001,192.168.3.158:7001,192.168.3.159:7001
#    timeout: 1000 # 连接超时时间（毫秒）
#    pool:
#      max-active: 10  # 连接池最大连接数（使用负值表示没有限制）
#      max-idle: 8     # 连接池中的最大空闲连接
#      min-idle: 2     # 连接池中的最小空闲连接
#      max-wait: 100   # 连接池最大阻塞等待时间（使用负值表示没有限制）       
    
    

mybatis:
  config-location: classpath:mybatis.cfg.xml
  mapper-locations: classpath*:com/open/**/dao/*.xml  


security:
  oauth2:
    token:
      store:
        type: redis


#设置最大超时时间
ribbon:  
  httpclient:
    enabled: false
  okhttp:
    enabled: true  
  ReadTimeout: 16000  
  ConnectTimeout: 16000 

#设置最大容错超时时间
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 16000


hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 16000

 
zuul:
  sensitive-headers: #/oauth/token需要请求头处理
  add-host-header: true
  routes:
    baidu:  
      path: /test163/**
      url: http://www.163.com 
    auth:  
      path: /auth/**
      service-id: open-auth-server 
      strip-prefix: false   
      custom-sensitive-headers: true  #http://blog.didispace.com/spring-cloud-zuul-cookie-redirect/ zuul授权码跳转问题
    client:  
      path: /apistore/**
      service-id: apistore
      strip-prefix: false  
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:1111/eureka/
      #http://192.168.3.170:1111/eureka,http://192.168.3.171:1111/eureka,http://192.168.3.173:1111/eureka
      #http://130.75.131.243:1111/eureka/,http://130.75.131.244:1111/eureka/,http://130.75.131.245:1111/eureka/   
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${spring.application.instance_id:${server.port}}
    lease-renewal-interval-in-seconds: 5
    #注册实例文档
    status-page-url: http://${spring.cloud.client.ipAddress}:${server.port}/swagger-ui.html # ${server.port}为该服务的端口号  
  
  


  
 